# Generated by Django 4.2.9 on 2024-02-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='anho',
            field=models.IntegerField(null=True, verbose_name='año'),
        ),
    ]
